<?php

namespace AppBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkIfUserRatedMovie($userId, $movieId){
        $query =$this->getEntityManager()->createQuery(''
                . 'SELECT r FROM AppBundle:Rating r WHERE r.user = :userId AND r.movie = :movieId')
                ->setParameters(array('userId' => $userId, 'movieId' => $movieId));
        $result = $query->getResult();
        $resultCount = count($result);
        if ($resultCount !=0){
            return true;
        }
        return false;
    }
}
